FROM php:8.4-cli-alpine

WORKDIR /app

RUN apk add --no-cache \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

COPY . .

ENTRYPOINT ["sh", "/app/docker-entrypoint.sh"]

EXPOSE 8080

CMD ["php", "-S", "0.0.0.0:8080", "-t", "public"]
